### ISSUE TITLE
rake db:seed_fu fails on Mac OS X Sierra

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#146]
As part of #145 users should setup a local development database that has been populated with data. The method that has been developed for this is a rake task `rake db:seed_fu`. However it fails with the following output on my machine:

```
~/G/massbuilds ❯❯❯ rake db:seed_fu                                                                                                                                      develop ✱

== Seed from /Users/mzagaja/GitHub/massbuilds/db/fixtures/organizations.rb
 - Organization {:id=>1, :name=>"Metropolitan Area Planning Council", :website=>"mapc.org", :location=>"Boston, MA", :email=>"info@mapc.org", :phone=>"617 933 0070", :address=>"60 Temple Place, Boston MA 02111", :short_name=>"MAPC", :abbv=>"MAPC", :municipal=>false}
rake aborted!
ActiveRecord::RecordNotSaved: Record not saved!
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `eval'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `block (2 levels) in seed'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `map'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `block in seed'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:35:in `seed'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/active_record_extension.rb:32:in `seed'
(eval):1:in `block (2 levels) in run_file'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `eval'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `block (2 levels) in run_file'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:58:in `block in open'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:57:in `open'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:57:in `open'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:36:in `block in run_file'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:35:in `run_file'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:26:in `block in run'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:25:in `each'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:25:in `run'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/seed-fu.rb:29:in `seed'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/seed-fu-2.3.5/lib/tasks/seed_fu.rake:36:in `block (2 levels) in <top (required)>'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/gems/airbrake-5.3.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/bin/ruby_executable_hooks:15:in `eval'
/Users/mzagaja/.rvm/gems/ruby-2.3.1@dd/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed_fu
(See full trace by running task with --trace)
```
@allthesignals suggests this might be because of a validation change. The seed file needs to be updated so it works.

**Comment by mzagaja** [comment]
Further investigation has revealed that the validations are the source of this error. The data is seeded from db/fixtures/organizations.rb. However manually running the organization addition in a rails console throws the following errors:

```
organization = Organization.new(id: 1, name: 'Metropolitan Area Planning Council', website: 'mapc.org', location: 'Boston, MA', email: 'info@mapc.org', phone: '617 933 0070', address: '60 Temple Place, Boston MA 02111', short_name: 'MAPC', abbv: 'MAPC', municipal: 'false')


ActiveRecord::RecordInvalid: Validation failed: Creator can't be blank, Website is not valid or not responding
```

In regards to the URL validation testing, when I manually run the following line:

`Net::HTTP.get_response(URI.parse('mapc.org'))
Errno::ECONNREFUSED: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)`

However it works if I try `Net::HTTP.get_response(URI.parse('http://www.mapc.org'))`

A temporary fix may be to use the url with http:// in front of it. However a separate issue should be opened to investigate and fix the URL validation so it can appropriately accommodate a wider variety of potential URL input, or the validation might be scrapped completely.

I am still investigating the source of the Creator validation error and how to fix it. If I comment out the creator presence validation it then complains that the user cannot be blank.
